# Rig Driver - Gas Town Plugin Manifest
name: driver
version: 0.2.0
description: |
  Hierarchical bead creation with enforced parent-child relationships.

  This plugin ensures consistent Epic -> Task -> Subtask hierarchy:
  - Blocks direct 'bd create' via Claude Code hook
  - Provides /bead skill with strict hierarchy enforcement
  - Consistent description format for auditability
  - Visual hierarchy confirmation after creation
type: coordination

author: "Jeremy Kalmus"
repository: "https://github.com/jeremykalmus/driver"

# Compatibility
gastown_version: ">=0.3.0"
requires: []

# Installation
install:
  script: "./install/install-driver.sh"

  options:
    default-type:
      description: "Default bead type when not specified"
      type: string
      enum: [task, bug, feature, epic]
      default: task

  creates:
    - driver/DRIVER-INSTRUCTIONS.md
    - driver/templates/
    - mayor/rig/driver/MAYOR-BRIEFING.md
    - polecats/driver/POLECAT-BRIEFING.md

  commands:
    - source: commands/bead.md
      targets:
        - .claude/commands/
        - mayor/.claude/commands/
        - refinery/.claude/commands/
        - polecats/.claude/commands/
        - crew/.claude/commands/

# Uninstallation
uninstall:
  script: "./install/uninstall-driver.sh"

# Slash commands provided
commands:
  bead:
    description: "Create beads with enforced hierarchy (Epic -> Task -> Subtask)"
    usage: "/bead <type> \"<title>\" [parent-id] [--spec \"<description>\"]"
    for: [driver, mayor, polecat, crew, refinery]
    file: commands/bead.md

# Configuration schema
config_schema:
  type: object
  properties:
    require-parent-for-tasks:
      type: boolean
      default: true
      description: |
        Require parent ID when creating tasks and bugs.
        Enforces Epic -> Task -> Subtask hierarchy.
  required: []

# Integration architecture
integration:
  # Hook-based enforcement
  hooks:
    PreToolUse:
      matcher: "Bash"
      action: "Block 'bd create' commands, redirect to /bead skill"
      script: ".claude/hooks/block-bd-create.sh"

  # Hierarchy enforcement
  hierarchy:
    epic: "Top-level container, no parent allowed"
    task: "Requires parent (epic or task)"
    bug: "Requires parent (epic or task)"

# Documentation
docs:
  readme: README.md
