# Rig Driver - Gas Town Plugin Manifest
name: driver
version: 0.1.0
description: |
  Coordination plugin for single-point-of-contact per rig.

  The Driver is your dedicated crew member that:
  - Triages incoming requests (quick fix, bug, feature, architecture)
  - Creates consistent beads (no more spec.md files)
  - Routes to appropriate workers (Keeper, Mayor, direct polecat)
  - Monitors epic progress until completion

  Talk to the Driver. Let the Driver talk to everyone else.
type: coordination

author: "Jeremy Kalmus"
repository: "https://github.com/jeremykalmus/driver"

# Compatibility
gastown_version: ">=0.3.0"
requires: []

# Installation
install:
  script: "./install/install-driver.sh"

  options:
    default-type:
      description: "Default bead type when not specified"
      type: string
      enum: [task, bug, feature, epic]
      default: task

  creates:
    - driver/DRIVER-INSTRUCTIONS.md
    - driver/templates/
    - mayor/rig/driver/MAYOR-BRIEFING.md
    - polecats/driver/POLECAT-BRIEFING.md

  commands:
    - source: commands/bead.md
      targets:
        - .claude/commands/
        - mayor/.claude/commands/
        - refinery/.claude/commands/
    - source: commands/triage.md
      targets:
        - .claude/commands/
    - source: commands/epic-status.md
      targets:
        - .claude/commands/
        - mayor/.claude/commands/

# Uninstallation
uninstall:
  script: "./install/uninstall-driver.sh"

# Slash commands provided
commands:
  bead:
    description: "Create consistent beads (replaces spec.md files)"
    usage: "/bead <type> <title> [--parent <id>] [--spec <inline or file>]"
    for: [driver, mayor, polecat, crew]
    file: commands/bead.md

  triage:
    description: "Classify request and recommend action"
    usage: "/triage <request description>"
    for: [driver, crew]
    file: commands/triage.md

  epic-status:
    description: "Check progress of an epic and its children"
    usage: "/epic-status <epic-id>"
    for: [driver, mayor]
    file: commands/epic-status.md

# Configuration schema
config_schema:
  type: object
  properties:
    auto-route:
      type: boolean
      default: true
      description: |
        Automatically route triaged requests to appropriate workers
        (Keeper for architecture, Mayor for work slinging)

    require-keeper-for-features:
      type: boolean
      default: false
      description: |
        Always route feature requests through Keeper first
  required: []

# Integration architecture
integration:
  # Single entry point
  entry:
    who: Driver
    receives: "All user requests for this rig"
    outputs:
      - "Beads (epics, issues, tasks)"
      - "Mail to Keeper (architecture)"
      - "Mail to Mayor (work slinging)"

  # Epic monitoring loop
  patrol:
    formula: "mol-driver-patrol"
    when: "Active epics exist"
    action: "Check progress, nudge blockers, report completion"

# Documentation
docs:
  readme: README.md
