#!/bin/bash
#
# Rig Driver - Installation Script
# Installs Driver coordination system on a Gas Town rig
#
# Usage: ./install-driver.sh [options] <rig-path>
#
# Options:
#   --skip-mayor       Don't install Mayor briefing
#   --skip-polecats    Don't install Polecat briefing
#   --skip-crew        Don't set up Driver crew member
#   --force            Overwrite existing files
#   -h, --help         Show this help message
#

set -e

# Colors for output
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
BLUE='\033[0;34m'
NC='\033[0m' # No Color

# Default values
FORCE=false
SKIP_MAYOR=false
SKIP_POLECATS=false
SKIP_CREW=false

# Get the directory where this script lives (driver plugin root)
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"

print_header() {
    echo -e "${BLUE}"
    echo "╔═══════════════════════════════════════════════════════════════╗"
    echo "║              Rig Driver - Installation                        ║"
    echo "║     Single point of contact for your Gas Town rig             ║"
    echo "╚═══════════════════════════════════════════════════════════════╝"
    echo -e "${NC}"
}

print_success() {
    echo -e "${GREEN}✓${NC} $1"
}

print_warning() {
    echo -e "${YELLOW}⚠${NC} $1"
}

print_error() {
    echo -e "${RED}✗${NC} $1"
}

print_info() {
    echo -e "${BLUE}→${NC} $1"
}

usage() {
    echo "Usage: $0 [options] <rig-path>"
    echo ""
    echo "Install Driver coordination system on a Gas Town rig."
    echo ""
    echo "This plugin provides:"
    echo "  - /bead command for consistent bead creation (all agents)"
    echo "  - /triage command for request classification"
    echo "  - /epic-status command for progress monitoring"
    echo "  - MAYOR-BRIEFING.md for Mayor bead protocols"
    echo "  - POLECAT-BRIEFING.md for Polecat status updates"
    echo "  - Driver crew member setup (optional)"
    echo ""
    echo "Options:"
    echo "  --skip-mayor       Don't install Mayor briefing/commands"
    echo "  --skip-polecats    Don't install Polecat briefing/commands"
    echo "  --skip-crew        Don't set up Driver crew member template"
    echo "  --force            Overwrite existing files"
    echo "  -h, --help         Show this help message"
    echo ""
    echo "Examples:"
    echo "  $0 ~/gt/myproject                    # Full install"
    echo "  $0 --skip-crew ~/gt/myproject        # Just commands, no crew"
    echo "  $0 --force ~/gt/myproject            # Reinstall everything"
}

# Parse arguments
while [[ $# -gt 0 ]]; do
    case $1 in
        --force)
            FORCE=true
            shift
            ;;
        --skip-mayor)
            SKIP_MAYOR=true
            shift
            ;;
        --skip-polecats)
            SKIP_POLECATS=true
            shift
            ;;
        --skip-crew)
            SKIP_CREW=true
            shift
            ;;
        -h|--help)
            usage
            exit 0
            ;;
        -*)
            print_error "Unknown option: $1"
            usage
            exit 1
            ;;
        *)
            RIG_PATH="$1"
            shift
            ;;
    esac
done

# Validate rig path
if [[ -z "$RIG_PATH" ]]; then
    print_error "No rig path specified"
    usage
    exit 1
fi

if [[ ! -d "$RIG_PATH" ]]; then
    print_error "Rig path does not exist: $RIG_PATH"
    exit 1
fi

# Resolve to absolute path
RIG_PATH="$(cd "$RIG_PATH" && pwd)"
RIG_NAME="$(basename "$RIG_PATH")"

# Check if this looks like a Gas Town rig
if [[ ! -f "$RIG_PATH/config.json" ]] && [[ ! -d "$RIG_PATH/.beads" ]] && [[ ! -d "$RIG_PATH/mayor" ]]; then
    print_warning "This doesn't look like a Gas Town rig (no config.json, .beads, or mayor)"
    read -p "Continue anyway? [y/N] " -n 1 -r
    echo
    if [[ ! $REPLY =~ ^[Yy]$ ]]; then
        exit 1
    fi
fi

print_header

echo "Installing Driver on rig: $RIG_NAME"
echo "Path: $RIG_PATH"
echo ""

# Step 1: Create driver directory structure
print_info "Creating Driver directory structure..."

mkdir -p "$RIG_PATH/driver"

print_success "Created driver/ directory"

# Step 2: Create driver config
print_info "Creating Driver configuration..."

DRIVER_CONFIG="$RIG_PATH/driver/driver.yaml"

if [[ -f "$DRIVER_CONFIG" ]] && [[ "$FORCE" != true ]]; then
    print_warning "Skipping driver.yaml (exists, use --force to overwrite)"
else
    cat > "$DRIVER_CONFIG" << EOF
# Rig Driver Configuration
# Generated by install-driver.sh on $(date +%Y-%m-%d)

driver:
  # Automatically route triaged requests to appropriate workers
  auto-route: true

  # Always require Keeper review for features (if Keeper installed)
  require-keeper-for-features: false

  # Default bead type when not specified
  default-type: task

# Installation metadata
installed:
  date: "$(date +%Y-%m-%d)"
  version: "0.1.0"
EOF
    print_success "Created driver.yaml"
fi

# Step 3: Install rig-level commands (available to all agents via rig .claude)
print_info "Installing rig-level commands..."

RIG_COMMANDS="$RIG_PATH/.claude/commands"
mkdir -p "$RIG_COMMANDS"

for cmd in bead.md triage.md epic-status.md; do
    src="$SCRIPT_DIR/commands/$cmd"
    dst="$RIG_COMMANDS/$cmd"

    if [[ -f "$dst" ]] && [[ "$FORCE" != true ]]; then
        print_warning "Skipping $cmd (exists, use --force to overwrite)"
    else
        if [[ -f "$src" ]]; then
            cp "$src" "$dst"
            print_success "Installed /$cmd to rig .claude/commands/"
        else
            print_error "Command not found: $src"
        fi
    fi
done

# Step 4: Install Mayor commands and briefing
if [[ "$SKIP_MAYOR" != true ]]; then
    print_info "Installing Mayor commands and briefing..."

    MAYOR_CLAUDE=""

    # Check for rig-level mayor
    if [[ -d "$RIG_PATH/mayor/rig/.claude" ]]; then
        MAYOR_CLAUDE="$RIG_PATH/mayor/rig/.claude"
        MAYOR_RIG="$RIG_PATH/mayor/rig"
    elif [[ -d "$RIG_PATH/mayor/rig" ]]; then
        MAYOR_CLAUDE="$RIG_PATH/mayor/rig/.claude"
        MAYOR_RIG="$RIG_PATH/mayor/rig"
        mkdir -p "$MAYOR_CLAUDE"
    fi

    if [[ -n "$MAYOR_CLAUDE" ]]; then
        mkdir -p "$MAYOR_CLAUDE/commands"
        cp "$SCRIPT_DIR/commands/bead.md" "$MAYOR_CLAUDE/commands/"
        cp "$SCRIPT_DIR/commands/epic-status.md" "$MAYOR_CLAUDE/commands/"
        print_success "Installed /bead to Mayor"
        print_success "Installed /epic-status to Mayor"

        # Install briefing
        mkdir -p "$MAYOR_RIG/driver"
        cp "$SCRIPT_DIR/MAYOR-BRIEFING.md" "$MAYOR_RIG/driver/"
        print_success "Installed MAYOR-BRIEFING.md"
    else
        print_warning "Mayor directory not found, skipping Mayor install"
    fi
fi

# Step 5: Install Polecat commands and briefing
if [[ "$SKIP_POLECATS" != true ]]; then
    print_info "Installing Polecat commands and briefing..."

    POLECAT_CLAUDE=""

    if [[ -d "$RIG_PATH/polecats/.claude" ]]; then
        POLECAT_CLAUDE="$RIG_PATH/polecats/.claude"
    elif [[ -d "$RIG_PATH/polecats" ]]; then
        POLECAT_CLAUDE="$RIG_PATH/polecats/.claude"
        mkdir -p "$POLECAT_CLAUDE"
    fi

    if [[ -n "$POLECAT_CLAUDE" ]]; then
        mkdir -p "$POLECAT_CLAUDE/commands"
        # Polecats only get /bead for discovered bugs
        cp "$SCRIPT_DIR/commands/bead.md" "$POLECAT_CLAUDE/commands/"
        print_success "Installed /bead to Polecats (for discovered bugs)"

        # Install briefing
        mkdir -p "$RIG_PATH/polecats/driver"
        cp "$SCRIPT_DIR/POLECAT-BRIEFING.md" "$RIG_PATH/polecats/driver/"
        print_success "Installed POLECAT-BRIEFING.md"
    else
        print_warning "Polecats directory not found, skipping Polecat install"
    fi
fi

# Step 6: Install Refinery commands
print_info "Installing Refinery commands..."

REFINERY_CLAUDE=""

if [[ -d "$RIG_PATH/refinery/rig/.claude" ]]; then
    REFINERY_CLAUDE="$RIG_PATH/refinery/rig/.claude"
elif [[ -d "$RIG_PATH/refinery/rig" ]]; then
    REFINERY_CLAUDE="$RIG_PATH/refinery/rig/.claude"
    mkdir -p "$REFINERY_CLAUDE"
fi

if [[ -n "$REFINERY_CLAUDE" ]]; then
    mkdir -p "$REFINERY_CLAUDE/commands"
    cp "$SCRIPT_DIR/commands/bead.md" "$REFINERY_CLAUDE/commands/"
    print_success "Installed /bead to Refinery"
else
    print_warning "Refinery directory not found, skipping Refinery install"
fi

# Step 7: Set up Driver crew member template (optional)
if [[ "$SKIP_CREW" != true ]]; then
    print_info "Setting up Driver crew member template..."

    CREW_DIR="$RIG_PATH/crew"

    if [[ -d "$CREW_DIR" ]] || [[ -d "$RIG_PATH/crew/.claude" ]]; then
        # Create template for driver crew member
        DRIVER_TEMPLATE="$RIG_PATH/driver/crew-template"
        mkdir -p "$DRIVER_TEMPLATE/agent"

        cp "$SCRIPT_DIR/agent/CLAUDE.md" "$DRIVER_TEMPLATE/agent/"

        cat > "$DRIVER_TEMPLATE/README.md" << 'EOF'
# Driver Crew Member Template

To create a Driver crew member:

```bash
# 1. Add the crew member
gt crew add driver

# 2. Copy the agent context
cp driver/crew-template/agent/CLAUDE.md crew/driver/agent/CLAUDE.md

# 3. Chat with your Driver
gt crew chat driver
```

The Driver is your single point of contact for this rig.
EOF

        print_success "Created crew-template/ for Driver crew member"
    else
        print_warning "Crew directory not found, skipping crew template"
    fi
fi

# Step 8: Create instructions file
print_info "Creating Driver instructions..."

cat > "$RIG_PATH/driver/DRIVER-INSTRUCTIONS.md" << 'EOF'
# Driver Installation Complete

## What Was Installed

Commands (available to all agents via /command):
- `/bead` - Create consistent beads with required format
- `/triage` - Classify requests and recommend actions
- `/epic-status` - Check epic progress and blockers

Briefings:
- `mayor/rig/driver/MAYOR-BRIEFING.md` - How Mayor should use beads
- `polecats/driver/POLECAT-BRIEFING.md` - How Polecats should update status

## The Bead Contract

Every bead MUST have:

```markdown
## Summary
What and why.

## Acceptance Criteria
- [ ] Testable criterion 1
- [ ] Testable criterion 2

## Context
Background, parent, Keeper ADR.

## Constraints
Technical limits, forbidden patterns.
```

## Creating a Driver Crew Member

If you want a dedicated Driver to talk to:

```bash
gt crew add driver
cp driver/crew-template/agent/CLAUDE.md crew/driver/agent/CLAUDE.md
gt crew chat driver
```

## Using Without a Dedicated Driver

All agents now have access to the commands. Mayor and Polecats have their
briefings. The standardization works even without a dedicated Driver crew member.
EOF

print_success "Created DRIVER-INSTRUCTIONS.md"

# Summary
echo ""
echo -e "${GREEN}════════════════════════════════════════════════════════════════${NC}"
echo -e "${GREEN}  Driver installation complete!${NC}"
echo -e "${GREEN}════════════════════════════════════════════════════════════════${NC}"
echo ""
echo "Installed to: $RIG_PATH"
echo ""
echo "Commands available:"
echo "  /bead <type> <title>     - Create consistent beads"
echo "  /triage <request>        - Classify and route requests"
echo "  /epic-status <epic-id>   - Check epic progress"
echo ""
echo "Next steps:"
echo "  1. Review driver/DRIVER-INSTRUCTIONS.md"
echo "  2. (Optional) Create Driver crew: gt crew add driver"
echo "  3. Start using /bead for all bead creation"
echo ""
